[package]
name = "http-404"
version = "1.3.2"
edition = "2021"

[dependencies]
async-signals = { version = "0.4" }
async-std = { version = "1.12", features = ["attributes"] }

[profile.release]
lto = true
codegen-units = 1
strip = true

[[bin]]
name = "http-404"
path = "src/main.rs"
