name: Publish

on:
  release:
    types:
      - published
  # workflow_dispatch:

jobs:
  publish-image:
    name: Publish container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GITHUB_REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/404
      DOCKER_REGISTRY_IMAGE: docker.io/aeron/404
    steps:
      - uses: actions/checkout@v7
      - id: recase
        uses: ASzc/change-string-case-action@v8
        with:
          string: ${{ env.GITHUB_REGISTRY_IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: >-
            linux/amd64,
            linux/arm64,
            linux/riscv64,
            linux/ppc64le,
            linux/s390x
          tags: |
            ${{ steps.recase.outputs.lowercase }}:latest
            ${{ steps.recase.outputs.lowercase }}:${{ github.ref_name }}
            ${{ env.DOCKER_REGISTRY_IMAGE }}:latest
            ${{ env.DOCKER_REGISTRY_IMAGE }}:${{ github.ref_name }}
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aeron/404
        continue-on-error: true
