name: Publish

on:
  release:
    types:
      - published
  # workflow_dispatch:

jobs:
  publish-image:
    name: Publish container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GITHUB_REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/404
      DOCKER_REGISTRY_IMAGE: docker.io/aeron/404
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: recase
        uses: ASzc/change-string-case-action@v4
        with:
          string: ${{ env.GITHUB_REGISTRY_IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        # HACK: https://github.com/docker/setup-qemu-action/issues/60
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          tags: >-
            ${{ steps.recase.outputs.lowercase }}:latest
            ${{ steps.recase.outputs.lowercase }}:${{ github.ref_name }}
            ${{ env.DOCKER_REGISTRY_IMAGE }}:latest
            ${{ env.DOCKER_REGISTRY_IMAGE }}:${{ github.ref_name }}
          platforms: linux/amd64, linux/arm64
          containerfiles: |
            ./Dockerfile
      - name: Log into GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Log into Docker Hub
        uses: redhat-actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to registries
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.build-image.outputs.tags }}
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REGISTRY_IMAGE }}
